### ISSUE TITLE
Critical Exception when running example code

### ISSUE THREAD

**Issue by jonathon-mcnabb** [fcodelabs/surround_sound#4]
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'Panner8739941456'
Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=ReferenceError: Can't find variable: Panner8739941456, WKJavaScriptExceptionColumnNumber=17, WKJavaScriptExceptionSourceURL=undefined, NSLocalizedDescription=A JavaScript exception occurred}, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
#2      MethodChannelWebViewPlatform.evaluateJavascript.<anonymous closure> (package:webview_flutter/src/webview_method_channel.dart)
<asynchronous suspension>

**Comment by medamarko** [comment]
Im also having same issue.
2021-04-20 20:24:43.335752+0200 Runner[983:828195] WF: _WebFilterIsActive returning: NO
2021-04-20 20:24:43.846529+0200 Runner[983:828387] [VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'Panner5126610836'
Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=ReferenceError: Can't find variable: Panner5126610836, WKJavaScriptExceptionColumnNumber=17, WKJavaScriptExceptionSourceURL=data:text/html;base64,PCFET0NUWVBFIGh0bWw+CjxodG1sIGxhbmc9ImVuIj4KPGhlYWQ+CiAgPG1ldGEgY2hhcnNldD0iVVRGLTgiPgogIDx0aXRsZT ... bWw+Cg==, NSLocalizedDescription=A JavaScript exception occurred}, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
#2      MethodChannelWebViewPlatform.evaluateJavascript.<anonymous closure> (package:webview_flutter/src/webview_method_channel.dart)
<asynchronous suspension>

**Comment by Ramesh-X** [comment]
Due to these issues, we downgraded the package to use web audio API. Also, issues in iOS are fixed now.
