### ISSUE TITLE
iOS problem

### ISSUE THREAD

**Issue by app-vrb** [fcodelabs/surround_sound#7]
Hi, when I run the app on iOS the first time I press Play or I move one of the slider I get this error:

[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'init_sound()'
Error Domain=WKErrorDomain Code=5 "JavaScript execution returned a result of an unsupported type" UserInfo={NSLocalizedDescription=JavaScript execution returned a result of an unsupported type}, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
<asynchronous suspension>
#2      SoundController.init (package:surround_sound/src/sound_controller.dart:31:5)
<asynchronous suspension>
#3      SoundController._check (package:surround_sound/src/sound_controller.dart:36:7)
<asynchronous suspension>
#4      SoundController.play (package:surround_sound/src/sound_controller.dart:41:5)
<asynchronous suspension>
#5      _HomePageState.build.<anonymous closure> (package:surroundsound/main.dart:44:19)
<asynchronous suspension>

Then it works correct, instead of on Android it's ok

**Comment by emmanuel-montoya** [comment]
I already fix it in fork for this repo in case you want to use it. https://github.com/Cyberneom/surround_frequency_generator
